// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mvc_assign5.Models;

namespace mvc_assign5.Migrations
{
    [DbContext(typeof(SettlementContext))]
    [Migration("20211128221220_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("mvc_assign5.Models.Settlement", b =>
                {
                    b.Property<int>("SettlementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<float>("vAmount")
                        .HasColumnType("real");

                    b.Property<string>("vIndicator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vSubMeasure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vTopic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vYear")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SettlementID");

                    b.ToTable("Settlements");
                });
#pragma warning restore 612, 618
        }
    }
}
